"""Transport Journey workflow rules."""

from app.modules.transport_journey.numbering import generate_trip_number
from app.modules.transport_journey.workflow import (
    CLOSED_STATUSES,
    RETURN_LEG_STATUSES,
    TRIP_TO_GO_WAYBILL_STATUS,
    TRIP_TO_RETURN_WAYBILL_STATUS,
    TRIP_TO_TRAILER_STATUS,
    TRIP_TO_TRUCK_STATUS,
    VALID_TRANSITIONS,
    InvalidTransitionError,
    ReturnWaybillRequiredError,
    StatusUpdatePlan,
    active_go_waybill_status_for_attached_trip,
    apply_status_date_effects,
    border_departure_auto_status,
    driver_status_for_trip,
    go_waybill_status_for_trip,
    is_driver_available,
    is_reopen_transition,
    is_trailer_available,
    is_truck_available,
    plan_status_update,
    return_waybill_status_for_trip,
    trailer_status_for_trip,
    truck_status_for_trip,
    trip_status_metadata,
    validate_status_transition,
)

__all__ = [
    "CLOSED_STATUSES",
    "RETURN_LEG_STATUSES",
    "TRIP_TO_GO_WAYBILL_STATUS",
    "TRIP_TO_RETURN_WAYBILL_STATUS",
    "TRIP_TO_TRAILER_STATUS",
    "TRIP_TO_TRUCK_STATUS",
    "VALID_TRANSITIONS",
    "InvalidTransitionError",
    "ReturnWaybillRequiredError",
    "StatusUpdatePlan",
    "active_go_waybill_status_for_attached_trip",
    "apply_status_date_effects",
    "border_departure_auto_status",
    "driver_status_for_trip",
    "generate_trip_number",
    "go_waybill_status_for_trip",
    "is_driver_available",
    "is_reopen_transition",
    "is_trailer_available",
    "is_truck_available",
    "plan_status_update",
    "return_waybill_status_for_trip",
    "trailer_status_for_trip",
    "truck_status_for_trip",
    "trip_status_metadata",
    "validate_status_transition",
]
