"""add_truck_table

Revision ID: 244dbc198b96
Revises: a1b2c3d4e5f6
Create Date: 2026-01-26 10:36:34.361516

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '244dbc198b96'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('truck',
    sa.Column('make', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('status', sa.Enum('idle', 'in_transit', 'maintenance', name='truckstatus'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('plate_number', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_truck_plate_number'), 'truck', ['plate_number'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_truck_plate_number'), table_name='truck')
    op.drop_table('truck')
    op.execute("DROP TYPE IF EXISTS truckstatus")
    # ### end Alembic commands ###
