"""update_waybill_id_to_uuid_and_add_table

Revision ID: 3e889b0528fa
Revises: a2b8c3d4e5f7
Create Date: 2026-01-29 16:53:42.555303

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '3e889b0528fa'
down_revision = 'a2b8c3d4e5f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waybill',
    sa.Column('waybill_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('client_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('origin', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('destination', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('expected_loading_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('open', 'in_progress', 'completed', 'invoiced', name='waybillstatus'), nullable=False),
    sa.Column('agreed_rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waybill_waybill_number'), 'waybill', ['waybill_number'], unique=True)
    op.alter_column('trip', 'waybill_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=True,
               postgresql_using='waybill_id::text::uuid')
    op.create_foreign_key(None, 'trip', 'waybill', ['waybill_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trip', type_='foreignkey')
    op.alter_column('trip', 'waybill_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_index(op.f('ix_waybill_waybill_number'), table_name='waybill')
    op.drop_table('waybill')
    # ### end Alembic commands ###
