"""add_cargo_type_to_waybill

Revision ID: 4222eccce346
Revises: 3e889b0528fa
Create Date: 2026-01-29 17:15:39.757271

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '4222eccce346'
down_revision = '3e889b0528fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('waybill', sa.Column('cargo_type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('waybill', 'cargo_type')
    # ### end Alembic commands ###
