"""add_payment_fields_to_expense

Revision ID: 54557c551aca
Revises: ca98886e9500
Create Date: 2026-02-01 10:41:20.883444

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '54557c551aca'
down_revision = 'ca98886e9500'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense_request', sa.Column('payment_method', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
    op.add_column('expense_request', sa.Column('payment_reference', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('expense_request', sa.Column('payment_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('expense_request', sa.Column('paid_by_id', sa.Uuid(), nullable=True))
    op.create_foreign_key('fk_expense_request_paid_by_id', 'expense_request', 'user', ['paid_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_expense_request_paid_by_id', 'expense_request', type_='foreignkey')
    op.drop_column('expense_request', 'paid_by_id')
    op.drop_column('expense_request', 'payment_date')
    op.drop_column('expense_request', 'payment_reference')
    op.drop_column('expense_request', 'payment_method')
    # ### end Alembic commands ###
