"""add_trip_number_to_trip

Revision ID: 5606b071a355
Revises: 2ded3840f140
Create Date: 2026-01-29 14:20:40.216671

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5606b071a355'
down_revision = '2ded3840f140'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expense_request_category'), table_name='expense_request')
    op.drop_index(op.f('ix_expense_request_created_by_id'), table_name='expense_request')
    op.drop_index(op.f('ix_expense_request_status'), table_name='expense_request')
    op.drop_index(op.f('ix_expense_request_trip_id'), table_name='expense_request')
    op.add_column('trip', sa.Column('trip_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.execute("UPDATE trip SET trip_number = 'LEGACY-' || id WHERE trip_number IS NULL")
    op.alter_column('trip', 'trip_number', nullable=False)
    op.drop_index(op.f('ix_trip_driver_id'), table_name='trip')
    op.drop_index(op.f('ix_trip_status'), table_name='trip')
    op.drop_index(op.f('ix_trip_trailer_id'), table_name='trip')
    op.drop_index(op.f('ix_trip_truck_id'), table_name='trip')
    op.create_index(op.f('ix_trip_trip_number'), 'trip', ['trip_number'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trip_trip_number'), table_name='trip')
    op.create_index(op.f('ix_trip_truck_id'), 'trip', ['truck_id'], unique=False)
    op.create_index(op.f('ix_trip_trailer_id'), 'trip', ['trailer_id'], unique=False)
    op.create_index(op.f('ix_trip_status'), 'trip', ['status'], unique=False)
    op.create_index(op.f('ix_trip_driver_id'), 'trip', ['driver_id'], unique=False)
    op.drop_column('trip', 'trip_number')
    op.create_index(op.f('ix_expense_request_trip_id'), 'expense_request', ['trip_id'], unique=False)
    op.create_index(op.f('ix_expense_request_status'), 'expense_request', ['status'], unique=False)
    op.create_index(op.f('ix_expense_request_created_by_id'), 'expense_request', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_expense_request_category'), 'expense_request', ['category'], unique=False)
    # ### end Alembic commands ###
