"""add_expense_metadata_to_expense_request

Revision ID: 5b2ccbd41b73
Revises: b4b37f9228db
Create Date: 2026-02-06 15:47:28.302989

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5b2ccbd41b73'
down_revision = 'b4b37f9228db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense_request', sa.Column('expense_metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expense_request', 'expense_metadata')
    # ### end Alembic commands ###
