"""add_exchange_rate_table_and_expense_audit_fields

Revision ID: 5c5580d8ab3d
Revises: 54557c551aca
Create Date: 2026-02-02 15:23:18.877978

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5c5580d8ab3d'
down_revision = '54557c551aca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_rate',
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('expense_request', sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), server_default='TZS', nullable=False))
    op.add_column('expense_request', sa.Column('exchange_rate', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('expense_request', sa.Column('approved_by_id', sa.Uuid(), nullable=True))
    op.add_column('expense_request', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'expense_request', 'user', ['approved_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expense_request', type_='foreignkey')
    op.drop_column('expense_request', 'approved_at')
    op.drop_column('expense_request', 'approved_by_id')
    op.drop_column('expense_request', 'exchange_rate')
    op.drop_column('expense_request', 'currency')
    op.drop_table('exchange_rate')
    # ### end Alembic commands ###
