"""add risk_level to waybill

Revision ID: 5d22a4b57512
Revises: 6d7e8f90a1b2
Create Date: 2026-02-05 05:26:13.975451

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5d22a4b57512'
down_revision = '6d7e8f90a1b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('waybill', sa.Column('risk_level', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False, server_default='Low'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('waybill', 'risk_level')
    # ### end Alembic commands ###
