"""add_waybill_id_and_current_location_to_trip

Revision ID: 8135bfc22462
Revises: 5606b071a355
Create Date: 2026-01-29 16:35:41.706999

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8135bfc22462'
down_revision = '5606b071a355'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip', sa.Column('waybill_id', sa.Integer(), nullable=True))
    op.add_column('trip', sa.Column('current_location', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trip', 'current_location')
    op.drop_column('trip', 'waybill_id')
    # ### end Alembic commands ###
