"""add_trailer_id_and_currency_to_maintenance_event

Revision ID: 8ca6b658a5c2
Revises: 5b2ccbd41b73
Create Date: 2026-02-07 19:42:52.500341

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8ca6b658a5c2'
down_revision = '5b2ccbd41b73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maintenance_event', sa.Column('trailer_id', sa.Uuid(), nullable=True))
    # Add currency as nullable first, then set default, then make NOT NULL
    op.add_column('maintenance_event', sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=True))
    op.execute("UPDATE maintenance_event SET currency = 'USD' WHERE currency IS NULL")
    op.alter_column('maintenance_event', 'currency', nullable=False)
    op.alter_column('maintenance_event', 'truck_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'maintenance_event', 'trailer', ['trailer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'maintenance_event', type_='foreignkey')
    op.alter_column('maintenance_event', 'truck_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('maintenance_event', 'currency')
    op.drop_column('maintenance_event', 'trailer_id')
    # ### end Alembic commands ###
