"""add transport master data tables (location, cargo_type, vehicle_status)

Revision ID: a2b8c3d4e5f7
Revises: 8135bfc22462
Create Date: 2026-01-29 18:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a2b8c3d4e5f7'
down_revision = '8135bfc22462'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Location table
    op.create_table('location',
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column('country', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_location_name'), 'location', ['name'], unique=False)

    # CargoType table
    op.create_table('cargo_type',
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_cargo_type_name'), 'cargo_type', ['name'], unique=True)

    # VehicleStatus table
    op.create_table('vehicle_status',
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_vehicle_status_name'), 'vehicle_status', ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicle_status_name'), table_name='vehicle_status')
    op.drop_table('vehicle_status')
    op.drop_index(op.f('ix_cargo_type_name'), table_name='cargo_type')
    op.drop_table('cargo_type')
    op.drop_index(op.f('ix_location_name'), table_name='location')
    op.drop_table('location')
    # ### end Alembic commands ###
