"""Add Client model

Revision ID: a3a26e8117ca
Revises: 5d22a4b57512
Create Date: 2026-02-05 18:38:25.317486

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a3a26e8117ca'
down_revision = '5d22a4b57512'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('system_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('tin', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_name'), 'client', ['name'], unique=False)
    op.create_index(op.f('ix_client_system_id'), 'client', ['system_id'], unique=True)
    
    # Create the enum type first if it doesn't exist
    sa.Enum('cash', 'transfer', name='paymentmethod').create(op.get_bind(), checkfirst=True)
    
    op.alter_column('expense_request', 'payment_method',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('cash', 'transfer', name='paymentmethod'),
               existing_nullable=True,
               postgresql_using='payment_method::paymentmethod')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('expense_request', 'payment_method',
               existing_type=sa.Enum('cash', 'transfer', name='paymentmethod'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.drop_index(op.f('ix_client_system_id'), table_name='client')
    op.drop_index(op.f('ix_client_name'), table_name='client')
    op.drop_table('client')
    # ### end Alembic commands ###
