"""add_driver_passport_and_expiry_fields

Revision ID: a51eaf4ef0b2
Revises: 2fbe05ddd438
Create Date: 2026-01-26 15:44:38.104444

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a51eaf4ef0b2'
down_revision = '2fbe05ddd438'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver', sa.Column('license_expiry_date', sa.DateTime(), nullable=True))
    op.add_column('driver', sa.Column('passport_number', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.add_column('driver', sa.Column('passport_expiry_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('driver', 'passport_expiry_date')
    op.drop_column('driver', 'passport_number')
    op.drop_column('driver', 'license_expiry_date')
    # ### end Alembic commands ###
