"""Add trip_expense_type table

Revision ID: b4b37f9228db
Revises: a3a26e8117ca
Create Date: 2026-02-06 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b4b37f9228db'
down_revision = 'a3a26e8117ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip_expense_type',
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_expense_type_name'), 'trip_expense_type', ['name'], unique=True)
    op.create_index(op.f('ix_trip_expense_type_category'), 'trip_expense_type', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trip_expense_type_category'), table_name='trip_expense_type')
    op.drop_index(op.f('ix_trip_expense_type_name'), table_name='trip_expense_type')
    op.drop_table('trip_expense_type')
    # ### end Alembic commands ###
