"""add_trailer_table

Revision ID: b62df7a91c03
Revises: a51eaf4ef0b2
Create Date: 2026-01-26 18:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b62df7a91c03'
down_revision = 'a51eaf4ef0b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trailer',
    sa.Column('type', sa.Enum('flatbed', 'skeleton', 'box', 'tanker', name='trailertype'), nullable=False),
    sa.Column('make', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('status', sa.Enum('idle', 'in_transit', 'maintenance', name='trailerstatus'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('plate_number', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trailer_plate_number'), 'trailer', ['plate_number'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trailer_plate_number'), table_name='trailer')
    op.drop_table('trailer')
    op.execute("DROP TYPE IF EXISTS trailerstatus")
    op.execute("DROP TYPE IF EXISTS trailertype")
    # ### end Alembic commands ###
