"""Add manager_comment to expense

Revision ID: ca98886e9500
Revises: 700ec93c7f85
Create Date: 2026-01-31 21:57:50.129053

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ca98886e9500'
down_revision = '700ec93c7f85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense_request', sa.Column('manager_comment', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expense_request', 'manager_comment')
    # ### end Alembic commands ###
