"""Change truck and trailer status to string

Revision ID: ccf9520125bd
Revises: 4222eccce346
Create Date: 2026-01-30 13:31:06.487909

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ccf9520125bd'
down_revision = '4222eccce346'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trailer', 'status',
               existing_type=postgresql.ENUM('idle', 'in_transit', 'maintenance', 'loading', 'at_border', 'offloaded', 'returned', 'waiting_for_pods', name='trailerstatus'),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('truck', 'status',
               existing_type=postgresql.ENUM('idle', 'in_transit', 'maintenance', 'loading', 'at_border', 'offloaded', 'returned', 'waiting_for_pods', name='truckstatus'),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    
    # Manual Fix for Role Enum migration
    # 1. Drop default constraint first
    op.alter_column('user', 'role', server_default=None)
    # 2. Convert type with explicit cast
    op.execute("ALTER TABLE \"user\" ALTER COLUMN role TYPE userrole USING role::userrole")
    # 3. Restore default (optional, depending on model)
    op.alter_column('user', 'role', server_default=sa.text("'ops'::userrole"))
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role',
               existing_type=sa.Enum('admin', 'manager', 'ops', 'finance', name='userrole'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'ops'::character varying"))
    op.alter_column('truck', 'status',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=postgresql.ENUM('idle', 'in_transit', 'maintenance', 'loading', 'at_border', 'offloaded', 'returned', 'waiting_for_pods', name='truckstatus'),
               existing_nullable=False)
    op.alter_column('trailer', 'status',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=postgresql.ENUM('idle', 'in_transit', 'maintenance', 'loading', 'at_border', 'offloaded', 'returned', 'waiting_for_pods', name='trailerstatus'),
               existing_nullable=False)
    # ### end Alembic commands ###
