"""Add attachments column

Revision ID: f365f4ebae82
Revises: 24dcd2d3f5e7
Create Date: 2026-02-11 22:02:21.136749

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f365f4ebae82'
down_revision = '24dcd2d3f5e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense_request', sa.Column('attachments', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expense_request', 'attachments')
    # ### end Alembic commands ###
